spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oab
    username: oab_user
    password: oab123
  batch:
    initialize-schema: ALWAYS

server:
 port : 8080
 
logging:
   file: C:/Users/axa8nzj/eclipse-workspace/application-debug.log
   level: 
      ca.homedepot.oab.fastfile: DEBUG